REG_MODEL = "movies_classifier/models/reg.pkl"
CLEAN_PIPE = "movies_classifier/models/cleaner.pkl"
LABEL_TRANS = "movies_classifier/models/label_transformer.pkl"
FULL_PIPE = "movies_classifier/models/full_pipe.pkl"

MOVIES_CSV = "movies_classifier/data/movies.csv"
X_TEST_NPY = "movies_classifier/data/X_test.npy"
X_TRAIN_NPY = "movies_classifier/data/X_train.npy"
Y_TEST_NPY = "movies_classifier/data/y_test.npy"
Y_TRAIN_NPY = "movies_classifier/data/y_train.npy"
